### PR TITLE
Manually update libjpeg-turbo pin

### PR DESCRIPTION
**Pull request by hmaarrfk**
This new version has an explicit constraint against jpeg
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carterbox** [comment]
This manual update to the pinning is because you want to change the libjpeg-turbo migration version to 2.1.5 without redoing the migration?

**Comment by hmaarrfk** [comment]
I mostly want to avoid future migration headaches

I think that redoing the migration might be the better way to go:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4199

^^^ Feel free to review and merge if you agree.

**Comment by hmaarrfk** [comment]
> without redoing the migration

I also didn't think of this until i made the 3 PRs.

**Comment by carterbox** [comment]
> ^^^ Feel free to review and merge if you agree.

I'm only staged-recipes, not core, so I can't sorry! 😄

**Pull request closed without merging**
